DROP TABLE CAMEROON IF EXISTS;
 
CREATE TABLE CAMEROON  (
  ID VARCHAR(10),  
  EMAIL VARCHAR(100),  
  PHONE_NUMBER VARCHAR(20),
  PARCEL_WEIGHT VARCHAR(10)
) ;

DROP TABLE ETHIOPIA IF EXISTS;
 
CREATE TABLE ETHIOPIA  (
  ID VARCHAR(10),  
  EMAIL VARCHAR(100),  
  PHONE_NUMBER VARCHAR(20),
  PARCEL_WEIGHT VARCHAR(10)
) ;

DROP TABLE MOROCOO IF EXISTS;
 
CREATE TABLE MOROCOO  (
  ID VARCHAR(10),  
  EMAIL VARCHAR(100),  
  PHONE_NUMBER VARCHAR(20),
  PARCEL_WEIGHT VARCHAR(10)
) ;

DROP TABLE MOZAMBIQUE IF EXISTS;
 
CREATE TABLE MOZAMBIQUE  (
  ID VARCHAR(10),  
  EMAIL VARCHAR(100),  
  PHONE_NUMBER VARCHAR(20),
  PARCEL_WEIGHT VARCHAR(10)
) ;

DROP TABLE UGANDA IF EXISTS;
 
CREATE TABLE UGANDA  (
  ID VARCHAR(10),  
  EMAIL VARCHAR(100),  
  PHONE_NUMBER VARCHAR(20),
  PARCEL_WEIGHT VARCHAR(10)
) ;